<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="BPELShippingReport" targetNamespace="http://xmlns.oracle.com/XXDMA/XxDmaOntShippingReport/BPELShippingReport" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/XXDMA/XxDmaOntShippingReport/BPELShippingReport" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>http://USSLTCSNL3303.solutions.glbsnet.com:8001/soa-infra/services/default/XxDmaOntShippingReport!1.0/BPELShippingReport.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="BPELShippingReport">
    <plnk:role name="BPELShippingReportProvider">
      <plnk:portType name="client:BPELShippingReport"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/XXDMA/XxDmaOntShippingReport/BPELShippingReport"
              schemaLocation="BPELShippingReport.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="BPELShippingReportRequestMessage">
    <wsdl:part name="payload" element="client:process"/>
  </wsdl:message>
  <wsdl:message name="BPELShippingReportResponseMessage">
    <wsdl:part name="payload" element="client:processResponse"/>
  </wsdl:message>
  <wsdl:portType name="BPELShippingReport">
    <wsdl:operation name="process">
      <wsdl:input message="client:BPELShippingReportRequestMessage"/>
      <wsdl:output message="client:BPELShippingReportResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BPELShippingReportBinding" type="client:BPELShippingReport">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="bpelshippingreport_client_ep">
    <wsdl:port name="BPELShippingReport_pt" binding="client:BPELShippingReportBinding">
      <soap:address location="http://localhost:7101/MARS-ViewController-context-root/ONTShipWarRpt_WLService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>