<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="BPELPoSpendReport" targetNamespace="http://xmlns.oracle.com/XXDMA/XXDmaPoSpendReport/BPELPoSpendReport" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/XXDMA/XXDmaPoSpendReport/BPELPoSpendReport" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>http://USSLTCSNL3303.solutions.glbsnet.com:8001/soa-infra/services/default/XXDmaPoSpendReport!1.0/BPELPoSpendReport.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="BPELPoSpendReport">
    <plnk:role name="BPELPoSpendReportProvider">
      <plnk:portType name="client:BPELPoSpendReport"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/XXDMA/XXDmaPoSpendReport/BPELPoSpendReport"
              schemaLocation="BPELPoSpendReport.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="BPELPoSpendReportRequestMessage">
    <wsdl:part name="payload" element="client:process"/>
  </wsdl:message>
  <wsdl:message name="BPELPoSpendReportResponseMessage">
    <wsdl:part name="payload" element="client:processResponse"/>
  </wsdl:message>
  <wsdl:portType name="BPELPoSpendReport">
    <wsdl:operation name="process">
      <wsdl:input message="client:BPELPoSpendReportRequestMessage"/>
      <wsdl:output message="client:BPELPoSpendReportResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BPELPoSpendReportBinding" type="client:BPELPoSpendReport">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="bpelpospendreport_client_ep">
    <wsdl:port name="BPELPoSpendReport_pt" binding="client:BPELPoSpendReportBinding">
      <soap:address location="http://localhost:7101/MARS-ApplicationController-context-root/PoSpendAnaRpt_WLService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>