<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="bpelGLPeriodLovProcess" targetNamespace="http://xmlns.oracle.com/XXDMA/XxDmaGLPeriodLov/bpelGLPeriodLovProcess" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/XXDMA/XxDmaGLPeriodLov/bpelGLPeriodLovProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>http://USSLTCSNL3303.solutions.glbsnet.com:8001/soa-infra/services/default/XxDmaGLPeriodLov!1.0/bpelGLPeriodLovProcess.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="bpelGLPeriodLovProcess">
    <plnk:role name="bpelGLPeriodLovProcessProvider">
      <plnk:portType name="client:bpelGLPeriodLovProcess"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/XXDMA/XxDmaGLPeriodLov/bpelGLPeriodLovProcess"
              schemaLocation="bpelGLPeriodLovProcess.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="bpelGLPeriodLovProcessRequestMessage">
    <wsdl:part name="payload" element="client:process"/>
  </wsdl:message>
  <wsdl:message name="bpelGLPeriodLovProcessResponseMessage">
    <wsdl:part name="payload" element="client:processResponse"/>
  </wsdl:message>
  <wsdl:portType name="bpelGLPeriodLovProcess">
    <wsdl:operation name="process">
      <wsdl:input message="client:bpelGLPeriodLovProcessRequestMessage"/>
      <wsdl:output message="client:bpelGLPeriodLovProcessResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="bpelGLPeriodLovProcessBinding" type="client:bpelGLPeriodLovProcess">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="bpelglperiodlovprocess_client_ep">
    <wsdl:port name="bpelGLPeriodLovProcess_pt" binding="client:bpelGLPeriodLovProcessBinding">
      <soap:address location="http://localhost:7101/MARS-ViewController-context-root/GlParamLov_WLService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>